{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kpodautoscaler.fullname" . }}-manager-role
  labels:
    {{- include "kpodautoscaler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling.kpodautoscaler.io
  resources:
  - kpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.kpodautoscaler.io
  resources:
  - kpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.kpodautoscaler.io
  resources:
  - kpodautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - custom.metrics.k8s.io
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
{{- end }} 