{{- if and .Values.controller.metrics.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kpodautoscaler.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kpodautoscaler.labels" . | nindent 4 }}
    control-plane: controller-manager
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - path: /metrics
    port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      {{- include "kpodautoscaler.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
{{- end }} 