{{- if .Values.controller.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kpodautoscaler.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kpodautoscaler.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "kpodautoscaler.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  type: ClusterIP
{{- end }} 