apiVersion: autoscaling.kpodautoscaler.io/v1alpha1
kind: KProxy
metadata:
  labels:
    app.kubernetes.io/name: kpodautoscaler
    app.kubernetes.io/managed-by: kustomize
  name: web-kproxy
  namespace: default
spec:
  targetRef:
    name: web
    port: 8080
    selector:
      app: web
  externalService:
    name: web-kproxy
    type: ClusterIP
    port: 80
  internalService:
    name: web-internal
  envoy:
    # Optional: Increase drain time for graceful shutdown
    drainSeconds: 30
